# Generated by Django 4.2.11 on 2025-11-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='RED-RED', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('max_post_length', models.IntegerField(default=2000)),
                ('max_comment_length', models.IntegerField(default=500)),
                ('max_bio_length', models.IntegerField(default=500)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('enable_stories', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_comments', models.BooleanField(default=True)),
                ('enable_likes', models.BooleanField(default=True)),
                ('auto_moderate', models.BooleanField(default=False)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_ban', 'Ban de Usuario'), ('user_unban', 'Unban de Usuario'), ('user_role_change', 'Cambio de Rol de Usuario'), ('post_delete', 'Eliminación de Post'), ('comment_delete', 'Eliminación de Comentario'), ('user_delete', 'Eliminación de Usuario'), ('config_change', 'Cambio de Configuración')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
