# Generated by Django 4.2.11 on 2025-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='enable_comments',
            new_name='allow_comments',
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='enable_likes',
            new_name='allow_follows',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_post_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='max_comment_length',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='max_post_length',
            field=models.IntegerField(default=5000),
        ),
    ]
