# Generated by Django 4.2.11 on 2025-11-04 16:49

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ban_reason_user_banned_at_user_is_banned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_cover_picture_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_picture_path),
        ),
    ]
