# Generated by Django 4.2.11 on 2025-11-26 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='live.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('live_stream', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StreamModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='live.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('live_stream', 'user')},
            },
        ),
    ]
